spring.application.name=formacion

spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/gestordearchivos
spring.datasource.username=postgres
spring.datasource.password=W300430f
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



aws.region=us-east-1
aws.bucket=documentos-bucket
aws.endpoint=http://localhost:4566
aws.accessKey=test
aws.secrerKey=test